[package]
name = "extapi-dpm"
version = "0.4.0"
edition = "2021"

[build-dependencies]
tonic-prost-build = "0.14"
protoc-bin-vendored = "3.2"

[dependencies]
async-stream = "0.3"
futures = "0.3.27"
futures-util = { version = "0.3", features = ["tokio-io"] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "time",
] }
tokio-stream = { version = "0.1", features = ["sync"] }

tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3"
tracing-futures = "0.2"

async-graphql = { version = "7", features = ["chrono"] }
async-graphql-axum = "7"
axum = { version = "0.8", features = ["ws"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
tower-http = { version = "0.6", features = [
    "cors",
    "compression-deflate",
    "decompression-deflate",
] }
http = "1"

chrono = "0.4"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
#jsonwebtoken = { version = "9.3", default-features = false }

reqwest.version = "0.12"
reqwest.default-features = false
reqwest.features = ["rustls-tls-webpki-roots", "json"]

rustls.version = "0.23"
rustls.features = ["ring"]

tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"
prost-types = "0.14"

clap = { version = "4.5", features = ["derive", "env"] }

kafka = { version = "0.10.0", default-features = false }

[dev-dependencies]
tower = "0.5"

[profile.release]
incremental = false
opt-level = 3
lto = true

[profile.dev]
incremental = false
debug = 1
opt-level = 2
lto = false

[lints.clippy]
enum_variant_names = "allow"
