[package]
name = "extapi-dpm"
version = "0.3.0"
edition = "2021"

[build-dependencies]
tonic-build = "0.13"

[dependencies]
async-stream = "0.3"
futures = "0.3.27"
futures-util = { version = "0.3", features = ["tokio-io"] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "rt",
    "time",
] }

tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3"
tracing-futures = "0.2"

async-graphql = { version = "7", features = ["chrono"] }
async-graphql-axum = "7"
axum = { version = "0.8", features = ["ws"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
tower-http = { version = "0.6", features = [
    "cors",
    "compression-deflate",
    "decompression-deflate",
] }
http = "1"

chrono = "0.4"

serde = { version = "1", features = ["derive"] }
jsonwebtoken = { version = "9.3", default-features = false }

tonic = "0.13"
prost = "0.13"
prost-types = "0.13"

[dev-dependencies]
tower = "0.5"

[profile.release]
incremental = false
opt-level = 'z'
lto = true

[profile.dev]
incremental = false
opt-level = 2
