[package]
name = "extapi-dpm"
version = "0.1.1"
edition = "2021"

[build-dependencies]
tonic-build = "0.12"

[dependencies]
futures = "0.3.27"
futures-util = { version = "0.3", features = ["tokio-io"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "rt", "time"] }

tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3"
tracing-futures = "0.2"

async-graphql = { version = "7", features = ["chrono"] }
async-graphql-warp = "7"
warp = { version = "0.3", features = [ "tls" ] }

chrono = "0.4"

tonic = "0.12"
prost = "0.13"
prost-types = "0.13"

#sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-rustls"] }

[profile.dev]
incremental = false
opt-level = 2
