[package]
name = "extapi-dpm"
version = "0.4.0"
edition = "2021"

[build-dependencies]
tonic-prost-build = "0.14"
protoc-bin-vendored = "3.2"

[dependencies]
async-stream = "0.3"
futures = "0.3.27"
futures-util = { version = "0.3", features = ["tokio-io"] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "rt",
    "time",
] }
tokio-stream = { version = "0.1", features = ["sync"] }

tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3"

async-graphql = { version = "7", features = ["chrono"] }
async-graphql-axum = "7"
axum = { version = "0.8", features = ["ws"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
tower-http = { version = "0.6", features = [
    "cors",
    "compression-deflate",
    "decompression-deflate",
] }
http = "1"

chrono = "0.4"

serde_json = "1"
base64 = "0.22"

tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"
prost-types = "0.14"

clap = { version = "4.5", features = ["derive", "env"] }

rust-pubsub-lib = { git = "https://github.com/fermi-ad/rust-pubsub-lib.git", tag = "v2.0.0" }
rust-env-var-lib = { git = "https://github.com/fermi-ad/rust-env-var-lib.git", tag = "v1.0.0" }

[dev-dependencies]
tower = "0.5"

[profile.release]
incremental = false
opt-level = 3
lto = true

[profile.dev]
incremental = false
debug = 1
opt-level = 2
lto = false

[lints.clippy]
enum_variant_names = "allow"
